### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by edwinb-ai** [edwinb-ai/LeastSquaresSVM#32]
We should create some simple benchmarks using [`BenchmarkTools.jl`](https://github.com/JuliaCI/BenchmarkTools.jl) where we can show how well our implementations do performance-wise.

The benchmarks should be made to show the following. The benchmarks should test the classification and regression implementations.
- [ ] The performance (**time**) against the well-established LibSVM solver.
- [ ] The performance (**memory**) against the well-established LibSVM solver.
- [ ] A baseline benchmark before #30 is implemented.

Maybe a couple of `Pluto.jl` notebooks should suffice for this.

**Comment by edwinb-ai** [comment]
Hey @gmagannaDevelop , so I've been thinking about this one and I will close this issue, and the main work on this matter
will be carried out on this repository
https://github.com/edwinb-ai/LSSVM-benchmarks

There are some reasons for this:
- I don't want to add more dependencies to this package.
- It is easier to just add dependencies, and test all the methods we want in a new, clean environment.
- All things regarding benchmarking can be discussed there.
In any case, you are welcome to join me there and test out some stuff. Thanks!

**Comment by gmagannaDevelop** [comment]
Hello @edwinb-ai! I had been busy with school this week. You may have noticed that I already forked [LSSVM-benchmarks](https://github.com/edwinb-ai/LSSVM-benchmarks). I hope to have more time during the weekend to join you. Greetings !
