### ISSUE TITLE
No docs ?

### ISSUE THREAD

**Issue by gmagannaDevelop** [edwinb-ai/LeastSquaresSVM#9]
F :cry:

**Comment by edwinb-ai** [comment]
> F cry

Would you like to use the package? I haven't been able to write up the docs, but it is fairly easy if you know MLJ.jl or if you check out the following [test file](https://github.com/edwinb-ai/Elysivm/blob/main/test/integrationtests.jl) @gmagannaDevelop 

I'll try to work on the docs as soon as I can.

**Comment by gmagannaDevelop** [comment]
I am currently busy with many assignments, but I would love to use it within Dextrose.jl
Don't worry about the docs, I'll open a new issue if I encounter any trouble whilst using the package.
Cheers
